name: Stock Data Scraper

on:
  schedule:
    # 每天 UTC 時間 01:00（台灣時間 09:00）執行
    - cron: '0 1 * * *'
  workflow_dispatch:  # 手動觸發

jobs:
  scrape-stock-data:
    runs-on: ubuntu-latest

    steps:
    # 1. 下載你的程式碼
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. 設定 Python 環境
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # 3. 安裝必要套件（不用 requirements.txt）
    - name: Install dependencies
      run: |
        pip install selenium
        pip install webdriver-manager

    # 4. 執行你的 Selenium 爬蟲程式
    - name: Run the scraper
      run: |
        python static.py
        python api.py

    # 5. Commit & Push 結果
    - name: Commit and push results
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "headphone0308"
        git config --global user.email "headphone0308@github.com"
        git add .
        git commit -m "Update stock data"
        git push
